name: CI

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: runs python
      run: python --version

    - name: run application
      run: python app.py